name: syl-transport-system
   services:
   - name: web
     source_dir: /
     github:
       repo: notyburin27/syl-system
       branch: main
     run_command: npm start
     environment_slug: node-js
     instance_count: 1
     instance_size_slug: basic-xxs
     build_command: npm run build
     routes:
     - path: /